# Generated by Django 4.0.4 on 2022-06-16 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0003_alter_comment_date_freepost_freecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freecomment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devapp.freepost'),
        ),
    ]
